# This workflow is triggered on push to the main branch and on pull requests
# to the main branch. It runs all tests, builds a Docker image, and deploys
# the test coverage report to GitHub Pages.
name: Validate pull requests to main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build_app:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write      # To deploy to Pages
      id-token: write   # To verify the deployment originates from an appropriate source
    environment:        # Deploy to the github-pages environment
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Create app folder
        run: |
          mkdir -p app
          cd app

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build app
        run: ./build.sh

  deploy_app:
    name: Deploy application to pages
    needs: build_app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write      # To deploy to Pages
      id-token: write   # To verify the deployment originates from an appropriate source
    environment:        # Deploy to the github-pages environment
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '../index.html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
