# This workflow is triggered on push to the main branch. It builds the application
# and deploys it to GitHub Pages.
name: Push update to main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_app:
    name: Build and deploy application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write      # To deploy to Pages
      id-token: write   # To verify the deployment originates from an appropriate source
    environment:        # Deploy to the github-pages environment
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Create app folder
        run: |
          mkdir -p app
          cd app

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build app
        run: ./build.sh

      - name: Wrap application for deployment
        run: |
          cd ..
          mkdir -p pages
          mv index.html pages/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '../pages'

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
